---
- name: Generate Health report of the systems
  hosts: all
  become: false

  tasks:
    - name: uptime check
      command: uptime
      register: uptime_output

    - name: Get disk Utilisation
      command: df -h
      register: disk_uti

    - name: Get free memory
      command: free -m
      register: free_memory

    - name: Create report line
      set_fact:
        report_content: |
          =============================================================
          =================== System Health Report ====================
          =============================================================
          Hostname: "{{ inventory_hostname }}"
          ------------------------------------
          ------------------------------------
          Uptime :-
          "{{ uptime_output.stdout }}"
          -------------------------------------------------------------
          Free Memory :-
          "{{ free_memory.stdout }}"
          -------------------------------------------------------------
          Disk Utilisation :-
          "{{ disk_uti.stdout }}"

    - name: Append report to the file on control_nade
      delegate_to: localhost
      run_once: false
      lineinfile:
        path: "./Health_Report_{{ ansible_date_time.date }}.txt"
        line: "{{ report_content }}"
        create: yes
        insertafter: EOF
